---
environment:
    referenceObject: 'TABLE_4'
    setReferenceWithoutOrientation: true
    toasterSimuObjects: ['PLACEMAT_1', 'PLACEMAT_2']
    pdgObjects: ['RED_CUBE2', 'BLUE_CUBE2', 'RED_CUBE', 'BLUE_CUBE', 'GREEN_CUBE', 'STICK']
    objectsRelativePose:
        PLACEMAT_1:
            x: 0.0
            y: 0.087
            z: 0.75
            rotation: false
        PLACEMAT_2:
            x:  0.0
            y: -0.087
            z: 0.75
            rotation: false
        RED_CUBE2:
            x: 0.201
            y: 0.6339
            z: 0.75
            rotation: false
        BLUE_CUBE2:
            x: 0.09
            y: 0.4912
            z: 0.75
            rotation: false
        RED_CUBE1:
            x: -0.1308
            y: -0.4312
            z: 0.75
            rotation: false
        BLUE_CUBE1:
            x: -0.1256
            y: -0.6222
            z: 0.75
            rotation: false
        GREEN_CUBE:
            x: 0.00058
            y: -0.1608
            z: 0.75
            rotation: false
        STICK:
            x: 0.2146
            y: 0.4036
            z: 0.75
            rotation: true
